<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['php_app_description'] = 'Приложение PHP обеспечивает инструментами управления для базовой технологии веб-сервера PHP.';
$lang['php_app_name'] = 'PHP';
