#!/bin/sh

# Set expose_php to prevent version leak
#---------------------------------------

CHECK=`grep -i "^expose_php[[:space:]]*=[[:space:]]*On" /etc/php.ini`
if [ -n "$CHECK" ]; then
    logger -p local6.notice -t installer "app-php-core - setting expose_php to prevent version leak"
    sed -i -e "s/^expose_php[[:space:]]*=.*/expose_php = Off/" /etc/php.ini
fi
