<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['php_app_description'] = 'The PHP app provides management tools for the underlying PHP web server technology.';
$lang['php_app_name'] = 'PHP';
