<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['php_app_description'] = 'Aplikacja PHP dostarcza narzędzia do zarządzania dostępnym serwerem WWW.';
$lang['php_app_name'] = 'PHP';
